VANTA.BIRDS({
  el: ".birds",
  mouseControls: true,
  touchControls: true,
  gyroControls: true,
  minHeight: 200.0,
  minWidth: 200.0,
  scale: 1.0,
  scaleMobile: 1.0,
  color2: 0xff00f0,
  backgroundAlpha: 0.0,
  quantity: 1.4,
  wingSpan: 40,
  sparation: 100,
});
